### ISSUE TITLE
Bug: Bindings have `mbedtls_` prefix

### ISSUE THREAD

**Issue by gbryant-arm** [veracruz-project/rust-mbedtls#1]
The bindings are generated with the `mbedtls_` prefix, which isn't the case on upstream `rust-mbedtls`.

Snippet from `bindings.rs`:

* Upstream (https://github.com/fortanix/rust-mbedtls/):
  ```
  extern "C" { # [link_name = "\u{1}mbedtls_debug_set_threshold"] pub fn debug_set_threshold (threshold : :: types :: raw_types :: c_int) ; }
  ```
* Downstream (https://github.com/veracruz-project/rust-mbedtls):
  ```
  extern "C" { pub fn mbedtls_debug_set_threshold (threshold : :: types :: raw_types :: c_int) ; }
  ```

This results in some errors, here for instance `debug_set_threshold` is not found in https://github.com/veracruz-project/rust-mbedtls/blob/egrimley/mbedtls/mbedtls/src/lib.rs#L159 because the symbol doesn't get exported with a prefix.

**Comment by egrimley-arm** [comment]
In https://github.com/veracruz-project/veracruz/pull/526 I've added the `mbedtls_` prefix in several places, including in `mbedtls_debug_set_threshold`.

The removal of the `mbedtls_` prefix was intentionally stopped by 12e1071097c33a2d608feaf50c33c7b5a768d53d. The commit message doesn't explain my original motivation for this, which was a collision of two symbols: I think there was a `something` and an `mbedtls_something` which collided after `mbedtls_` was removed (with the updated version of the C library). But I find it generally a bit easier to grep the code for a symbol when symbols don't get magically modified. It's true that `mbedtls_sys::mbedtls_something` is a bit verbose, but there's the alternative (used in 19 files) where you do `use mbedtls_sys::*;` and then just refer to `mbedtls_something`, instead of the previous approach of doing `use mbedtls_sys;` and then referring to `mbedtls_sys::something`, so it's actually a bit more concise in some cases without the prefix trimming.

Do we want to keep this issue open or close it with this explanation?
